### ISSUE TITLE
Review and move from "beta" to "RC"

### ISSUE THREAD

**Issue by Paddy0174** [Paddy0174/lovelace-ui-minimalist#1]
This issue is to cover the changes/additions/deletions while moving from "beta" state to "release candidate", a task list, if you will.

- [x] `card-media-player*` needs to be reviewed and tested
- [x] is the structure for `custom-cards` and the description in [custom-cards.md](../custom-cards.md) ok? Changes needed?
- [x] faults/errors in [readme.md](../readme.md)?
- [x] descriptions all good?
- [x] page [example.md](../example.md) needs to be "written"
- [x] page [custom-cards.md](../custom-cards.md) needs to be reviewed
- [x] *<ins>new items from here downwards / 25.09.21</ins>*
- [x] *readme.md* check TOC is working, links correct, no headers missing
- [x] *readme.md* check all links on page
- [x] *readme.md* descriptions missing (or wrong)
  - [x] card media player with controls (missing)
  - [x] description in accordance to issue #3 
- [ ] *readme.md* pictures missing (or wrong)
  - [ ] chip icon only (missing)
  - [ ] chip icon with state (missing)
  - [ ] chip icon with double state (missing)
  - [x] card generic (generic pic needed, actual pic is card battery)
  - [x] card generic swap (missing and wrong)
  - [ ] card input boolean (missing)
  - [ ] card media player with cover art (missing)
  - [x] card battery (see card generic)
  - [ ] card media player with controls (missing)
- [x] *readme.md* check code in usage -> example/variables is correct:
  - [x] variables missing in readme.md vs. `button_card_templates`
  - [x] variables missing in description
  - [x] entity necessary 
- [x] *readme.md* check code in template is the same as in `button_cards_template` for each definition

Please add to this issue whatever comes to mind.

**Comment by schumijo** [comment]
- Media player cards reviewed and tested
- Custom cards structure and custom-cards.md reviewed.
I think we need to clarify language file
Flower custom card posted as exemple

**Comment by Paddy0174** [comment]
Added to the list:
* *readme.md* check TOC is working, links correct, no headers missing
* *readme.md* check all links on page
* *readme.md* descriptions missing (or wrong)
  * card media player with controls (missing)
  * description in accordance to issue #3 
* *readme.md* pictures missing (or wrong)
  * chip icon only (missing)
  * chip icon with state (missing)
  * chip icon with double state (missing)
  * card generic (generic pic needed, actual pic is card battery)
  * card generic swap (missing and wrong)
  * card input boolean (missing)
  * card media player with cover art (missing)
  * card battery (see card generic)
  * card media player with controls (missing)
* *readme.md* check code in usage -> example/variables is correct:
  * variables missing in readme.md vs. `button_card_templates`
  * variables missing in description
  * entity necessary 
* *readme.md* check code in template is the same as in `button_cards_template` for each definition

**Comment by Paddy0174** [comment]
Moved to the new repo, [here](https://github.com/UI-Lovelace-Minimalist/UI/issues/5).
